<?php require('template/header.phtml');?>

    </div
</div>

<div class="container bg-light shadow my-5" id="desktop">
    <div class="row">
        <div class="col-sm-12 py-3">
            <a href="email.php">
                <div class="card border-0 bg-light" style="width: 70px">
                    <img class="card-img-top" src="images/email.png" alt="email icon">
                    <p class="text-center text-reset">EMail</p>
                </div>
            </a>
        </div>
        <div class="col-sm-12 py-3">
            <a href="webbrowser.php">
                <div class="card border-0 bg-light" style="width: 70px">
                    <img class="card-img-top" src="images/web.png" alt="web icon">
                    <p class="text-center text-reset">Web</p>
                </div>
            </a>
        </div>
        <div class="col-sm-12 py-3">
            <a href="files.php">
                <div class="card border-0 bg-light" style="width: 70px">
                    <img class="card-img-top" src="images/files.png" alt="files icon">
                    <p class="text-center text-reset">Files</p>
                </div>
            </a>
        </div>
        <div class="col-sm-12 py-3" id="waste-bin">
            <div class="card border-0 bg-light" style="width: 70px">
                <img class="card-img-top" src="images/trash.png" alt="email icon">
                <p class="text-center text-reset">Waste Bin</p>
            </div>
        </div>
    </div>
</div>

<?php require('template/footer.phtml') ?>
