<?php require('template/header.phtml') ?>

<form name="index" action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">

    <div class="col-12 padding">
        <h1 class="display-4 text-center">WELCOME !</h1>
    </div>
    <hr>
    <div class="container-fluid padding">
        <div class="row padding">
            <div class="col-lg-6">
                <h2>What is Phishing?</h2>
                <p>Phishing is a broad term which involves a large range of strategies which hackers use to trick you
                    into handing out sensitive information, usually passwords, credentials or financial information -
                    and it is highly likely that everyone you know will have experienced this to a degree at some point
                    in their lives!</p>
                <p>Definition of Phishing –
                    <q>the fraudulent practice of sending emails purporting to be from reputable
                        companies in order to induce individuals to reveal personal information, such as passwords and
                        credit card numbers.</q>
                    – Oxford Dictionary</p>
            </div>
            <div class="col-lg-6">
                <figure>
                    <img src="images/section1.jpg" alt="IMAGE 1" class="img-fluid">
                </figure>
            </div>
        </div>
    </div>
    <hr class="my-4">
    <div class="container-fluid padding">
        <div class="row padding">
            <div class="col-lg-6">
                <figure>
                    <img src="images/section2.jpg" alt="IMAGE 2" class="img-fluid">
                </figure>
            </div>
            <div class="col-lg-6">
                <h2>How important is it?</h2>
                <p>Phishing has only increased in prevalence during the boom of the digital age, and has been increasing ever since, it comes in many forms and is not limited to just emails! A general rule is that if it can be exploited, then it will!</p>

                <p>From the 1990s to the current day – cyber-crime continues to grow, and phishing attacks remain to be the <strong>biggest current cyber threat</strong>, despite the continuous acts to prevent cybercrime by professionals and large corporations. All these companies can do is preventative measures; however, it still relies on you, the consumer - to keep yourself safe from fraudsters!</p>

                <p>The biggest weakness is someone with their guard down.</p>
                <p>Remember, <strong>if it’s too good to be true, then it is.</strong></p>

                <p>Unfortunately, as development of preventative methods increases – so does the complexity of these attacks, and most people simply are not tech savvy enough to keep up!</p>

                <p>The old and the vulnerable are the most desirable targets for those who are looking to exploit people.</p>
                <p><strong>So watch out, and always take caution to be safe online</strong>.</p>
            </div>
        </div>
    </div>
    <hr class="my-4">
    <div class="container-fluid padding">
        <div class="row padding">
            <div class="col-lg-6">
                <h2>Important information to be aware of</h2>
                <p>Research has shown from the email security firm Barracuda that phishing attacks via email have drastically gone up 667% due to the ongoing COVID-19 pandemic as of August 2020, although the more recent figures will likely be much more staggering.</p>

                <p>There are many methods, and they are usually quite simple - we can define them quite clearly below:</p>
                <ul>
                    <li>Vishing – Voice/Phone Phishing.</li>
                    <li>Smishing – SMS/Text Phishing.</li>
                    <li>Phishing – Phishing via email.</li>
                    <li>Spear phishing – Phishing directly targeted at you via any of these methods (includes name for example or a company you work with or have a relation to)</li>
                </ul>

            </div>
            <div class="col-lg-6">
                <figure>
                    <img src="images/section3.jpg" alt="IMAGE 3" class="img-fluid">
                </figure>
            </div>
        </div>
    </div>
    <hr class="my-4">
    <div class="container-fluid padding">
        <div class="row padding">
            <div class="col-lg-6">
                <figure>
                    <img src="images/section4.jpg" alt="IMAGE 2" class="img-fluid">
                    <figcaption>Photo by <a class="text-reset" href="https://unsplash.com/@austindistel?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Austin Distel</a> on <a class="text-reset" href="https://unsplash.com/s/photos/email?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></figcaption>
                </figure>
            </div>
            <div class="col-lg-6">
                <h2>Key phishing signs to watch out for</h2>
                <p>Any communication which insists that:</p>
                <ul>
                    <li><strong>Immediate action must be taken</strong> – they are trying to rush you into making a hasty and poorly thought out decision.</li>

                    <li><strong>Financial penalisation</strong> – they are trying to scare you into giving them money, just in case!</li>

                    <li><strong>Financial incentives</strong> – they are trying to take advantage of those who need help! By helping themselves to your credit card information! Do not click their links or enter any details!</li>

                    <li><strong>Spelling/Grammar mistakes</strong> - poor spelling and grammar skills are usually indication of a scam.</li>

                    <li><strong>Impersonations</strong> – they will usually pretend to be a company that is reputable and that you can trust, so you will hand over your information without suspecting a thing!</li>
                </ul>
                <p>You can learn more by navigating through our website.
                The purpose is not only to educate, but to have fun while learning!
                    Hopefully you will be able to apply the skills which you will learn here, to prevent cybercrime from taking place!</p>

            </div>
        </div>
    </div>
</form>
<?php require('template/footer.phtml') ?>
