<?php require('template/header.phtml'); ?>


    <div class="register">
        <h1>Register</h1>
        <form action="register.php" method="post">

            <input type="text" name="email" placeholder="Email">
            <span class="invalidFeedback">
                <?php echo $view->users['emailError']; ?>
            </span>

            <input type="text" name="firstname" placeholder="First Name">
            <span class="invalidFeedback">
                <?php echo $view->users['firstnameError']; ?>
            </span>

            <input type="text" name="lastname" placeholder="Last Name">
            <span class="invalidFeedback">
                <?php echo $view->users['lastnameError']; ?>
            </span>

            <input type="password" name="password" placeholder="Password">
            <span class="invalidFeedback">
                <?php echo $view->users['passwordError']; ?>
            </span>

            <input type="password" name="confirmPassword" placeholder="Confirm Password">
            <span class="invalidFeedback">
                <?php echo $view->users['confirmPasswordError']; ?>
            </span>

            <input type="submit" value="Register">
            <p class="option">Already registered? <a href="login.php">Login</a></p>

        </form>
    </div>

<?php require('template/footer.phtml') ?>