<?php require('template/header.phtml'); ?>


    <div class="webbrowser">
        <div class="row">
            <div class="col-xs-12">

                <div class="container">
                    <ul class="nav justify-content-center">
                        <li class="nav-item" id="webbrowser-info"
                            title="<h3>Step 1</h3><p>Before you start, read the information page to learn a few necessary steps to spot fake websites.</p><button class='btn btn-info' type='button' id='web-guide-2-next'>Next</button>">
                            <a class="nav-link" href="#" onclick="changeImg('images/web-info.png')">Info</a>
                        </li>
                        <li class="nav-item" id="webbrowser-page" web-guide-step="2"
                            title="<h3>Step 2</h3><p>The following four tabs display examples of the scam mentioned in the information page.</p><button class='btn btn-info' type='button' id='web-guide-3-next'>Next</button>">
                            <a class="nav-link" href="#" onclick="changeImg('images/web-linkedin.png')">http://www.Iinkdin.com/</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#" onclick="changeImg('images/web-paypal.png')">https://www.paypal.com/</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#" onclick="changeImg('images/web-deal.png')">https://www.currys.co.uk/mac</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#" onclick="changeImg('images/web-checkout.png')">https://www.currys.co.uk/checkout</a>
                        </li>
                    </ul>
                </div>

                <div class="container">
                    <div class="col-md-12 px-0">
                        <img id="change_img_target" class="img-fluid" src="images/web-linkedin.png">
                    </div>
                </div>

            </div>
        </div>
    </div>

    <h3 id="webbrowser-test" web-guide-step="3"
        title="<h3>Step 3</h3><p>Once you have familiarized yourself with the information and the webpage, please answer the following question. You will be able to see your score on the profile page. </p><button class='btn btn-info' type='button' id='web-guide-4-next'>Close</button>">Please answer which of the above pages raising the following concerns: </h3>

    <form action="webbrowser.php" method="post" class="padding">
        <div class="container-fluid">
            <div class="row">
                <div class="card-body col-md-3">
                    <h6>Unreliable Address Bar</h6>
                    <input list="browsers" name="browser1" required>
                    <datalist id="browsers">
                        <option value="LinkedIn">
                        </option><option value="PayPal">
                        </option><option value="Currys.co.uk/Mac">
                        </option><option value="Currys.co.uk/checkout">
                        </option></datalist>
                </div>

                <div class="card-body col-md-3">
                    <h6>Unreliable Content</h6>
                    <input list="browsers" name="browser2" required>
                    <datalist id="browsers">
                        <option value="LinkedIn">
                        </option><option value="PayPal">
                        </option><option value="Currys.co.uk/Mac">
                        </option><option value="Currys.co.uk/checkout">
                        </option></datalist>
                </div>

                <div class="card-body col-md-3">
                    <h6>Suspicious Deal</h6>
                    <input list="browsers" name="browser3" required>
                    <datalist id="browsers">
                        <option value="LinkedIn">
                        </option><option value="PayPal">
                        </option><option value="Currys.co.uk/Mac">
                        </option><option value="Currys.co.uk/checkout">
                        </option></datalist>
                </div>

                <div class="card-body col-md-3>">
                    <h6>Alarming Payment Method</h6>
                    <input list="browsers" name="browser4" required>
                    <datalist id="browsers">
                        <option value="LinkedIn">
                        </option><option value="PayPal">
                        </option><option value="Currys.co.uk/Mac">
                        </option><option value="Currys.co.uk/checkout">
                        </option></datalist>
                </div>

                <input type="submit" name="submit">

            </div>
        </div>
    </form>

    <script>
        function changeImg(url) {
            document.getElementById("change_img_target").src = url;
        }
    </script>

<?php require('template/footer.phtml') ?>