    </div>
</div>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
    <script src="js/bootstrap.bundle.min.js"></script>
    <?php
    if (isset($view->scripts)) {
        foreach ($view->scripts as $script) {
            echo "<script src=\"$script\"></script>";
        }
    }
    ?>
    <footer>
    <div class="container-fluid">
        <div class="row text-center">
            <div class="col-md-4">
            <hr class="light">
            <h5>The Website</h5>
                <hr class="light">
                <p>This website is created</p>
                <p>for educational purposes</p>
                <p>&copy; All Rights Reserved</p>
            </div>
            <div class="col-md-4">
                <hr class="light">
                <h5>Contacts</h5>
                <hr class="light">
                <p><a href="mailto:A.Koser@edu.salford.ac.uk">A.Koser@edu.salford.ac.uk</a></p>
                <p><a href="mailto:G.Jones20@edu.salford.ac.uk">G.Jones20@edu.salford.ac.uk</a></p>
                <p><a href="mailto:P.Savchev@edu.salford.ac.uk">P.Savchev@edu.salford.ac.uk</a></p>
                <p><a href="mailto:A.Roberts11@edu.salford.ac.uk">A.Roberts11@edu.salford.ac.uk</a></p>
                <p><a href="mailto:D.T.Lewis@edu.salford.ac.uk">D.T.Lewis@edu.salford.ac.uk</a></p>
            </div>
            <div class="col-md-4">
                <hr class="light">
                <h5>About Us</h5>
                <hr class="light">
                <p><a href="https://www.salford.ac.uk/">The University of Salford</a></p>
                <p>Salford,</p>
                <p>Manchester,</p>
                <p>United Kingdom</p>
            </div>
            <div class="col-12">
                <hr class="light">
                <h3>&copy; Group 8</h3>
            </div>
        </div>
    </div>
    </footer>
</body>
</html>